/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Glowbox 3D (https://sketchfab.com/glowbox3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-computer-desk-c67f61fa444044bcb88ec3e28f0ca7ac
Title: Low Poly Computer Desk
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

const HackerRoom = props => {
  const { nodes, materials } = useGLTF('/models/low-poly-computer-desk.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029_Material_0.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
};

useGLTF.preload('/models/low-poly-computer-desk.glb');

export default HackerRoom;
